#!/bin/sh

while [ $# -gt 0 ]; do
    pattern=$1
    target=$(which "$pattern" 2>/dev/null)
    if [ $? -eq 0 ]; then
        $EDITOR "$target"
    else
        results="$(find -L "$LOCALBIN" -maxdepth 1 -type f -iname "*${pattern}*" -print0 | xargs -0)"
        if [ -n "$results" ]; then
            $EDITOR $results;
        fi
    fi
    shift
done
