#!/bin/bash

r1=$((RANDOM % 256))
g1=$((RANDOM % 256))
b1=$((RANDOM % 256))

case "${1}" in
    -c) #complementary
        r2=$((256 - r1))
        g2=$((256 - g1))
        b2=$((256 - b1))
        ;;
    -rr) #rotated
        r2=${b1}
        g2=${r1}
        b2=${g1}
        ;;
    -rl) #rotated the other way
        r2=${g1}
        g2=${b1}
        b2=${r1}
        ;;
    *)  #random
        r2=$((RANDOM % 256))
        g2=$((RANDOM % 256))
        b2=$((RANDOM % 256))
        ;;
esac

angle="$((RANDOM % 360))"

color1="$(printf '#%06x' "$((b1 + (256 * g1) + (65536 * r1)))")"
color2="$(printf '#%06x' "$((b2 + (256 * g2) + (65536 * r2)))")"

[[ -n $DEBUG ]] && printf '%s) %s - %s\t%d°\t[%d.%d.%d - %d.%d.%d]\n' "${color1}" "${color2}" "${angle}" "${r1}" "${g1}" "${b1}" "${r2}" "${g2}" "${b2}"

hsetroot -add "${color1}" -add "${color2}" -gradient "${angle}"
