#!/bin/sh

if [ $(pgrep -cx hud) -gt 1 ]; then
    printf '%s\n' "The panel is already running." >&2
    exit 1
fi
trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

test -e "$HUD_FIFO" && rm "$HUD_FIFO";
mkfifo "$HUD_FIFO";

# functions
_battery() {
    while true; do
        output="B: ";
        case "$(acpi -a | cut -d: -f2)" in
            *off-line*)
                case "$(acpi | cut -d' ' -f3)" in
                    Discharging*)
                        case "$(acpi | tr -d' ' | cut -d, -f2)" in
                            *100*)   output="${output}\\\\\\\\\\" ;;
                            [8-9]*) output="${output}\\\\\\\\\\" ;;
                            [6-7]*) output="${output}\\\\\\\\-" ;;
                            [4-5]*) output="${output}\\\\\\--" ;;
                            [2-3]*) output="${output}\\\\---" ;;
                            1*)     output="${output}\\----" ;;
                            *)      output="${output}-----" ;;
                        esac
                        ;;
                esac
                ;;
            *on-line*)
                case "$(acpi | tr -d ' ' | cut -d, -f2)" in
                    *100*) ;;
                    [8-9]*) output="${output}/////" ;;
                    [6-7]*) output="${output}////-" ;;
                    [4-5]*) output="${output}///--" ;;
                    [2-3]*) output="${output}//---" ;;
                    1*)     output="${output}/----" ;;
                    *)      output="${output}-----" ;;
                esac
                ;;
        esac
        printf '%s\n' "${output}";
        sleep 10;
    done
}
_clock() {
    while true; do
        date +'T%a %H:%M';
        sleep 30;
    done
}
_wifi() {
    while true; do
        output="W";
        if iw $(ip link show|grep 'state UP'|cut -d: -f2) info >/dev/null 2>&1;
        then
            case "$(awk 'NR==3{print $3}' /proc/net/wireless)" in
                10*)    output="${output})))))" ;;
                [8-9]*) output="${output})))))" ;;
                [6-7]*) output="${output}))))-" ;;
                [4-5]*) output="${output})))--" ;;
                [2-3]*) output="${output}))---" ;;
                1*)     output="${output})----" ;;
                *)      output="${output}-----" ;;
            esac
           # output="${output}$(awk 'NR==3{print $3}' /proc/net/wireless)";
        fi
        printf '%s\n' "${output}";
        sleep 5;
    done
}

_battery > "$HUD_FIFO" &
_clock   > "$HUD_FIFO" &
_wifi    > "$HUD_FIFO" &

while IFS= read -r line; do
    case "$line" in
        T*) # Time
            clock=" ${line#?} "
        ;;
        B*) # Battery
            battery=" ${line#?} "
        ;;
        W*) # Wifi
            wifi=" ${line#?} "
        ;;
        N*) # Notification
            notification=" ${line#?} "
        ;;
        X*) # XMonad
            xmonad=" ${line#?} "
        ;;
    esac
    printf '%s %s %s\n' \
        "%{l}${xmonad}"  \
        "%{c}${clock}"    \
        "%{r}${notification} ${wifi}${battery}";
done < "$HUD_FIFO" |\
    lemonbar -n hud -d -f "-*-terminus-*-*-*-*-12-*-*-*-*-*-*-*" \
             -F "#f0f0f0" -B "#222222" | sh &

wait;
