#!/bin/bash

(( $EUID == 0 )) || exit 1

cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.old

if curl -o /etc/pacman.d/mirrorlist 'https://www.archlinux.org/mirrorlist/?country=US&protocol=https&ip_version=4'; then
  echo "Success"
else
  echo ":("
fi

sed -i 's/^#//' /etc/pacman.d/mirrorlist;
