#!/usr/bin/env bash
# from zx2c4 (pass writer)

shopt -s nullglob globstar

typeit=0
if [[ $1 == "--type" ]]; then
    typeit=1;
    shift;
fi

prefix=${PASSWORD_STORE_DIR:-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | dmenu "$@")

[[ -n $password ]] || exit 1

if [[ $typeit -eq 0 ]]; then
    pass show -c "$password" 2>/dev/null;
    notify-send.sh "Copied $password to clipboard." \
                   "Will clear in 45 seconds."
else
    pass show "$password" | { read -r pass; printf %s "$pass"; } | xdotool type --clearmodifiers --file -
fi
