#!/bin/sh
# because I change shit too much
# as of now, it only does a few things
# because that's really all I need to do
# TODO: detect package manager & use it ?

CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/bauerbill/bauerbill.json"
BUILDDIR="$HOME/builds/bauerbill"
mkdir -p $CONFIGDIR $BUILDDIR 2>/dev/null

manager=bauerbill
bauerbill_opts=("--bb-config" "${CONFIG}"
                "--build-dir" "${BUILDDIR}")

_add_bauerbill() {
    sudo bauerbill ${bauerbill_opts[@]} -S --aur "${@}";
    if [ -x "$BUILDDIR/download.sh" ]; then
        echo "Downloading AUR packages..."
        command cd $BUILDDIR
        ./download.sh && rm download.sh
        command cd -

    fi
    if [ -x "$BUILDDIR/build.sh" ]; then
        command cd $BUILDDIR
        ./build.sh && rm build.sh
        command cd -
    fi
}

_remove_bauerbill() {
    sudo bauerbill -R "${@}";
}

_search_bauerbill() {
    bauerbill -Ss --aur "${@}" 2>/dev/null || {
        echo "Didn't find anything." >&2
    }
}

_update_bauerbill() {
    sudo bauerbill -Syyu --aur "${@}";
}

_clean_pacman() {
    if pacman -Qqdtt; then
        sudo pacman -Rs $(pacman -Qqdtt)
    else
        echo "Nothing to clean." >&2;
    fi
}
_clean_bauerbill() { _clean_pacman "${@}" ; }

# main
case "$1" in
    add)    shift; _add_${manager}    "${@}" ;;
    remove) shift; _remove_${manager} "${@}" ;;
    search) shift; _search_${manager} "${@}" ;;
    update) shift; _update_${manager} "${@}" ;;
    clean)  shift; _clean_${manager}         ;;
    *)             $manager "${@}"           ;;
esac
