#!/bin/sh
cachedir=${XDG_CACHE_HOME:-"$HOME/.cache"}
if [ -d "$cachedir" ]; then
	cache=$cachedir/dmenu_run
else
	cache=$HOME/.dmenu_cache # if no xdg dir, fall back to dotfile in ~
fi
APP=$(
	IFS=:
	if stest -dqr -n "$cache" $PATH; then
		stest -flx $PATH | sort -u | tee "$cache" | dmenu "$@"
	else
		dmenu "$@" < "$cache"
	fi
) | ${SHELL:-"/bin/sh"} &

termdir="${XDG_CONFIG_DIR:-"$HOME/.config"}"
if [ -d "$termdir" ]; then
    termfile=$termdir/dmenu_terminal
else
    termfile=$HOME/.dmenu_term
fi
grep -qw "${APP}" "$termfile" && {
    ${TERMINAL:-xterm} -e "${APP}"
} || {
    echo "${APP}" | ${SHELL:-"/bin/sh"} &
}
