#!/usr/bin/env bash
# adapted from z3bra

test -z "$1" && exit

W3MIMGDISPLAY="/usr/lib/w3m/w3mimgdisplay"
FILENAME="$1"
FONTH=14
FONTW=8
COLUMNS=$(tput cols)
LINES=$(tput lines)

read width height <<EOF 
  $(printf '5;%s' "$FILENAME" | $W3MIMGDISPLAY)
EOF

max_width=$((FONTW * COLUMNS))
max_height=$((FONTH * $((LINES - 2))))

if (( $width > $max_width )); then
  height=$((height * max_width / width))
  width=$max_width
fi
if (( $height > $max_height )); then
  width=$((width * max_height / height))
  height=$max_height
fi

w3m_command="0;1;0;0;$width;$height;;;;;$FILENAME\n4;\n3;"

tput clear
tput cup $height 0
echo -e "$w3m_command" | $W3MIMGDISPLAY
