#!/bin/bash

output() {
    if v=$(amixer sget Master | grep -E 'Playback.*\[on\]'); then
        s=$(awk '{print $4}' <<< $v)
        case $s in
            '[100%]') s="[100]" ;;
            *) ;;
        esac
    else
        s="%{F#888888}[---]%{F-}"
    fi

    printf '%s\n' $s
}

case "$1" in
    toggle)
        amixer sset Master toggle;
        xmonadctl refresh-panel;
        ;;
    display)
        urxvtc -geometry 32x20+1000+20 \
               -name alsamixer -e alsamixer;
        ;;
    *) output ;;
esac
