#!/bin/bash

if [[ "$1" == -m ]]; then
  read px py <<END
      $(wmp)
END
  dmenu="dmenu -l 10 -x $px -y $py -w 300"
else
  dmenu="dmenu -l 10"
fi

bspc query -N -n .window |\
  grep -vi "$(pfw)" |\
  xargs xtitle |\
  $dmenu |\
  xargs wmctrl -a
